movies/urls.py
from django.urls import path
from . import view2
app_name="movies"

urlpatterns =[
    path('', view2.main, name="main"),
    path('moviePickUp/', view2.moviePickUp, name="pickup"),
    path('search/', view2.search, name="search"),
    path('<int:id>/', view2.detail, name="detail"),
    path('<int:id>/comment/create/',view2.commentCreate, name="commentCreate"),
    path('<int:id>/comments/<int:comment_id>/delete/', view2.commentDelete, name='commentDelete'),
    path('<int:id>/score/create/',view2.scoreCreate, name="scoreCreate"),
    path('person/', view2.person, name="person"),
]

todal/urls.py
from django.urls import path, include
from django.contrib import admin
from movies import views
urlpatterns = [
    path('', views.main),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    poster_path = models.CharField(max_length=150)
    tmd_id = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    overview = models.TextField()
    production_company = models.CharField(max_length=50)
    homepage = models.CharField(max_length=150)
    release_date = models.CharField(max_length=50)
    backdrop_path = models.CharField(max_length=150)
    director = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.TextField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)


class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.IntegerField()

movies/forms.py
from django import forms
from .models import Movie,Comment,Score

class SearchForm(forms.ModelForm):
    # class Meta:
    #     model = Movie
    #     fields = ['name',]
    word = forms.CharField(label="Movie Name",max_length=30)
    

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        
class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        # comment만 입력받기
        fields = ['content']
        

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
import requests
import os
from movies.models import Movie, Comment, Score
from movies.forms import SearchForm, MovieForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import json
import urllib.request
from urllib.parse import quote
# Create your views here.



# 영화 데이터 수집용 페이지 - 사용자는 알 필요없음
def moviePickUp(request):
    # the movie db key
    TMD_KEY = '37a3092ff9c0a61c3819bc65e4ab09c5'

    # 영화 리스트를 여러 페이지 가져오기
    for n in range(1, 6):
        num = str(n)
        # 영화 목록 url
        LIST_URL = f"https://api.themoviedb.org/3/discover/movie?api_key={TMD_KEY}&language=ko-KR&page={num}"
        listData = requests.get(LIST_URL)
        resDatas = listData.json().get('results')
        request = urllib.request.Request(LIST_URL)
        response = urllib.request.urlopen(request)


        for resData in resDatas:
            # 영화의 TMD id
            tmd_id = resData.get('id')
            # 영화 detail url
            DETAIL_URL = f"https://api.themoviedb.org/3/movie/{tmd_id}?api_key={TMD_KEY}&language=ko-KR"
            detailData = requests.get(DETAIL_URL)
            # 영화 감독 //
            CREDITS_URL = f"https://api.themoviedb.org/3/movie/{tmd_id}/credits?api_key={TMD_KEY}"
            creditsData = requests.get(CREDITS_URL)
            resdirectors = creditsData.json().get('crew')

            for n in range(5):
                # job이 Director인 사람의 이름 찾기
                if resdirectors[n].get('job') == 'Director':
                    director = resdirectors[n].get('name')
                    break
                else:
                    director = ""
            # // 영화 감독

            # 영화 회사정보
            resDetailData = detailData.json().get('production_companies')
            if resDetailData:
                company = resDetailData[0].get('name')
            else:
                # 영화 회사 정보가 없는 경우
                company = ""

            # 홈페이지가 있는경우와 없는 경우 구분
            # print(detailData.json().get('homepage'))
            if detailData.json().get('homepage') != None:
                homepage = detailData.json().get('homepage')
                # print(homepage)
            else:
                homepage = ""

            # 장르가 있는지 없는지
            if detailData.json().get('genres'):
                genre = detailData.json().get('genres')[0].get('name')
            else:
                genre = ""

            Movie.objects.get_or_create(
                title=resData.get('title'),
                backdrop_path="https://image.tmdb.org/t/p/original" + resData.get('backdrop_path'),
                poster_path="https://image.tmdb.org/t/p/original" + resData.get('poster_path'),
                overview=detailData.json().get('overview'),
                release_date=detailData.json().get('release_date'),
                genre=detailData.json().get('genres')[0].get('name'),
                production_company=company,
                tmd_id=tmd_id,
                director=director,
                homepage=homepage,
            )
    return render(request, 'movies/moviePickUp.html')


def main(request):
    # pagination //
    movie_list = Movie.objects.get_queryset().order_by('id')
    paginator = Paginator(movie_list, 20)  # Show 20 contacts per page
    page = request.GET.get('page')
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        movies = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        movies = paginator.page(paginator.num_pages)
    # // pagination

    # search기능 ############################################
    movie = Movie.objects.get_queryset().order_by('id')
    # GET request의 인자중에 searchword값이 있으면 가져오고, 없으면 빈 문자열 넣기
    if request.method == "GET":
        searchword = request.GET.get('searchword', '')
        resultMovie = []

        if searchword:  # searchword가 있다면
            searchMovie = movie.filter(title__contains=searchword)  # 제목에 searchword가 포함된 레코드만 필터링
            if searchMovie:
                # 영화 여러개 저장위해 데이터의 개수 
                movie_count = searchMovie.count()
                for c in range(movie_count):
                    # 데이터들 resultMovie리스트에 저장
                    # 원본 주석처리
                    # resultMovie.append({searchMovie[c].title:searchMovie[c].id})
                    resultMovie.append({'title': searchMovie[c].title, 'id': searchMovie[c].id})
                    # 디테일 페이지 이동위해 id값도 넘겨준다
                # print(resultMovie)
                return render(request, 'movies/searchresult.html',
                              {'movie': movie, 'searchMovie': searchMovie, 'resultMovie': resultMovie})
            else:
                # 아무것도 입력하지 않는다면,
                return render(request, 'movies/searchresult.html', {'resultMovie': resultMovie})

        return render(request, 'movies/main.html', {'movies': movies})
    # mainpage에서는
    # <검색기능>작품의 제목,배우,감독을 검색해 해당 영화의 디테일 페이지로 연결하는 역할을 한다.
    # 일단 작품의 제목으로 검색하는 것을 구현 
    # <로그인버튼>
    #############################################################################3


def detail(request, id):
    movie = Movie.objects.get(id=id)
    # # 댓글 폼
    comment_form = CommentForm()
    ratings = 0
    # 평점
    for score in movie.score_set.all():
        ratings += score.rating
    if ratings == 0:
        ratingAvg = 0
    else:
        ratingAvg = ratings / movie.score_set.all().count()
    ratingAvg = round(ratingAvg, 2)

    # 추천 영화 보여주기 //
    TMD_KEY = os.getenv('37a3092ff9c0a61c3819bc65e4ab09c5')
    RECOMMEND_URL = f"https://api.themoviedb.org/3/movie/{movie.tmd_id}/recommendations?api_key={TMD_KEY}&language=ko-KR"
    recommendData = requests.get(RECOMMEND_URL)
    resRecommends = recommendData.json().get('results')

    # 영화 추천 //
    # 추천 영화가 5개보다 작을때와 클때로 구분
    res = []
    if (len(resRecommends) > 5):
        for i in range(5):
            ig = "https://image.tmdb.org/t/p/w500" + resRecommends[i].get('poster_path')
            url = resRecommends[i].get('id')
            if Movie.objects.filter(tmd_id=url):
                # 추천 영화가 db에 있다면
                recommend = Movie.objects.get(tmd_id=url)
                ul = recommend.id
            else:
                # 없으면 현재 페이지 영화 id 사용
                ul = id
            res.append({'ig': ig, 'ul': ul})
    else:
        for j in range(len(resRecommends)):
            ig = "https://image.tmdb.org/t/p/w500" + resRecommends[j].get('poster_path')
            url = resRecommends[j].get('id')
            if Movie.objects.filter(tmd_id=url):
                # 추천 영화가 db에 있다면
                recommend = Movie.objects.get(tmd_id=url)
                ul = recommend.id
            else:
                # 없으면 현재 페이지 영화 id 사용
                ul = id
            res.append({'ig': ig, 'ul': ul})
    # // 영화 추천
    return render(request, 'movies/detail.html',
                  {'movie': movie, 'comment_form': comment_form, 'res': res, "ratingAvg": ratingAvg})


def search(request):
    movie = Movie.objects.get_queryset().order_by('id')
    # GET request의 인자중에 searchword값이 있으면 가져오고, 없으면 빈 문자열 넣기
    if request.method == "GET":
        searchword = request.GET.get('searchword', '')
        resultMovie = []

        if searchword:  # searchword가 있다면
            searchMovie = movie.filter(title__contains=searchword)  # 제목에 searchword가 포함된 레코드만 필터링
            if searchMovie:
                # 영화 여러개 저장위해 데이터의 개수 
                movie_count = searchMovie.count()
                for c in range(movie_count):
                    # 데이터들 resultMovie리스트에 저장
                    # 원본 주석처리
                    # resultMovie.append({searchMovie[c].title:searchMovie[c].id})
                    resultMovie.append({'title': searchMovie[c].title, 'id': searchMovie[c].id})
                    # 디테일 페이지 이동위해 id값도 넘겨준다
                return render(request, 'movies/searchresult.html',
                              {'movie': movie, 'searchMovie': searchMovie, 'resultMovie': resultMovie})
            else:
                # 아무것도 입력하지 않는다면,
                return render(request, 'movies/searchresult.html', {'resultMovie': resultMovie})

        return render(request, 'movies/search.html')
    # mainpage에서는
    # <검색기능>작품의 제목,배우,감독을 검색해 해당 영화의 디테일 페이지로 연결하는 역할을 한다.
    # 일단 작품의 제목으로 검색하는 것을 구현 
    # <로그인버튼>


# 댓글 생성하기
@login_required
def commentCreate(request, id):
    #   # 댓글 작성 폼을 list에서 보여줌.
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        # 유저정보, 몇번 글 넣어야 하는지 전달할거니까 기다려
        movie = Movie.objects.get(id=id)
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.movie = movie
        comment.save()

    return redirect('movies:detail', id)


# 댓글 삭제하기
@login_required
def commentDelete(request, id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if comment.user != request.user:
        return HttpResponseForbidden("You are not allowed to delete this Comment")
    else:
        comment.delete()
    return redirect('movies:detail', id)


# 평점 등록하기
@login_required
def scoreCreate(request, id):
    rating = request.POST.get('rating')
    user = request.user
    movie = Movie.objects.get(id=id)
    score_list = Score.objects.filter(user=user, movie=movie)

    if score_list:
        score = score_list.update(rating=rating)
    else:
        score = Score.objects.create(user=user, movie=movie, rating=rating)

    return redirect('movies:detail', id)


# 오늘의 인물들을 보여주는 페이지
@login_required
def person(request):
    TMD_KEY = os.getenv('37a3092ff9c0a61c3819bc65e4ab09c5')
    PERSON_URL = f"https://api.themoviedb.org/3/person/popular?api_key={TMD_KEY}&language=ko-KR"

    personData = requests.get(PERSON_URL)

movies/templates/movies/detail.html
{% extends 'base.html'%}
<!--영화의 상세 내용을 나타내는 페이지-->

{% load bootstrap4 %}

{% block bb %}
    <div class="fontchange" style="font-family: 'Noto Sans KR', sans-serif;">
    <!--상단 이미지-->
    <div class="col-12 p-0">
    <img src="{{movie.backdrop_path}}" style="width:100%; height:500px; opacity:0.8"   />
    </div>
        
    <div class="container">
    <!--영화 제목-->
        <div class="pt-4">
            <span style="font-size:45px"><b>{{movie.title}}</b></span>
            <!--평점 예쁘게-->
            {% if ratingAvg >= 5 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i> {{ratingAvg}}점</a>
            {% elif ratingAvg >= 4.5 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star-half-alt text-warning"></i> {{ratingAvg}}점</a>
            {% elif ratingAvg >= 4 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="far fa-star text-warning"></i>{{ratingAvg}}점</a>
            {% elif ratingAvg >= 3.5 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"><i class="fas fa-star-half-alt text-warning"></i></i><i class="far fa-star text-warning"></i> {{ratingAvg}}점</a>
            {% elif ratingAvg >= 3 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i>{{ratingAvg}}점</a>
            {% elif ratingAvg >= 2.5 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="fas fa-star-half-alt text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i> {{ratingAvg}}점</a>
            {% elif ratingAvg >= 2 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i>{{ratingAvg}}점</a>
            {% elif ratingAvg >= 1.5 %}
                <a><i class="fas fa-star text-warning"></i><i class="fas fa-star-half-alt text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i> {{ratingAvg}}점</a>
            {% elif ratingAvg >= 1 %}
                <a><i class="fas fa-star text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i><i class="far fa-star text-warning"></i> {{ratingAvg}}점</a>
            {% endif %}
    
        <hr> 
        
            <span>지금까지 이 영화에 {{movie.score_set.all.count}}개의 별점이 쌓였어요! &nbsp; </span>
            {% if user.is_authenticated %}
                {% for score in movie.score_set.all %}
                    {% if score.user == request.user %}
                        <!--현재 로그인 유저가 작성한 별점-->
                        <span><b>{{score.user.username}}</b>님의 별+점 {{score.rating}}점</span>
                    {% endif %}
                {% endfor %}
                <!--별점 입력-->
                <p>{% include 'movies/rating.html' %} </p>
            {% endif %}
        </div>
       
        
            
        
        <!--영화 정보-->
        <div class="row my-5">
            <!--영화 이미지-->
            <div class="col-md-4 d-flex my-3">
                <img src="{{movie.poster_path}}"  style="width:100%; height:100%" />
            </div>
            <!--영화 정보-->
            <div class="col-md-8 d-flex my-3">
                <div>
                    <h5 class="mr-3">장르: {{movie.genre}}</h5>
                    <h5 class="mr-3">감독: {{movie.director}}</h5>
                    <h5 class="mr-3">제작사: {{movie.production_company}}</h5>
                    <h5 class="mr-3">개봉일: {{movie.release_date}}</h5>
                    <h5>관련 홈페이지: <a href="{{movie.homepage}}" target="_blank">{{movie.homepage}}</a></h5>
                    <h5>예매사이트:&nbsp;<a href='http://www.cgv.co.kr/search/?query={{movie.title}}' target="_blank" style="text-decoration:none"> <img src="/static/images/CGV_BI_bc.jpg" style="height:10%;width:10%"></a></h5>
                    <h5 class="mr-3">줄거리</h5><hr>
                    <p> {{movie.overview}}</p>
                </div>
            </div>
        </div>
        
 
        <hr>
        <p>지금까지 이 영화에 {{movie.comment_set.all.count}}개의 댓글이 있어요!</p>
        {% if user.is_authenticated %}
        
        <div class="col-10">
            <form action="{% url 'movies:commentCreate' movie.id %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                <input type="submit" value="작성" class="btn btn-warning btn-sm">
            </form>
        {% endif %}
        
        <hr>
        
        {% for comment in movie.comment_set.all %}
            <div class="inblockclass">
                <p style="display: inline-block">{{ comment.content }} &nbsp;</a> | <strong>{{comment.user.username}}</strong> <a class="font-weight-light">&nbsp; {{ comment.created_at }}</a></p>
                    
                <!--댓글 삭제-->
                {% if comment.user == user %}
                    <form method='POST' action="{% url 'movies:commentDelete' movie.id comment.id %}" style="display: inline-block ">
                        {% csrf_token %}
                        <input type="submit" value="삭제" class="btn btn-danger btn-sm"/>
                    </form>
                {% endif %}
            </div>
            <hr>
        {% endfor %}
        
        <!--연관 영화 이미지-->
        <p class="h3 my-3"><b>추천 영화</b></p>
        {% if res %}
            {% for r in res %}
                {% if r.ul == movie.id %}
                    <img src="{{r.ig}}" width="150" height="200" class="mr-3 mb-3"></img>
                {% else %}
                    <a href="{% url 'movies:detail' r.ul %}"><img src="{{r.ig}}" width="150" height="200" class="mr-3 mb-3"></img></a>
                {% endif %}
            {% endfor%}
        {% else %}
            <p>추천 영화가 없습니다.</p>
        {% endif %}
        </div>
    </div>    
{% endblock %}

movies/templates/movies/main.html
{% extends 'base.html' %}

{% block bb %}
      
    <div class="col-md-12 p-0">
        <!--나중에 이미지 바꾸고 크기 조정해야함 & 글자 가운데 정렬-->
        <img src="../static/images/search2.jpg" style="width:100%; height:600px"  >
        <div class="carousel-caption">
            <h1 class=" text-black mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s" style="font-family: 'Playfair Display SC';text-shadow: 1px 2px gray;">Reflix</h1>
            <br><br><br>
            <!--영화 검색 -->
            <div class="justify-content-center">
                <form method="GET" class="d-flex justify-content-center">
                    <i class="fas fa-search fa-2x"></i>
                    <input type="text" name="searchword" value="{{searchword}}" placeholder=" 작품 제목을 검색해보세요." class="shadow-lg rounded border border-dark w-75 p-2" style="font-family: 'Noto Sans KR', sans-serif;">
                </form>
            </div>
        </div>
    </div>
    
        <!--영화 목록-->
    <div class="container">
        
        <h2 class="text-center mt-5" style="font-family: 'Playfair Display SC';text-decoration: underline; "><b>movie list</b></h2>
        <br><br><br>
        <div class="row border border-dark my-3">
        {% for movie in movies %}
            <div class=" col-md-4 col-lg-3 my-3" >
                <div class="d-flex justify-content-center mt-4"> 
                    <a href="{% url 'movies:detail' movie.id %}">
                        <img src="{{movie.poster_path}}"class="card-img-top" alt="..." style="height:305px; width:200px" id="mainImg" >
                    </a>
                </div>
                <div class="card-body">
                    <h6 class="card-title text-center" ><strong>{{movie.title|truncatechars:15}}</strong></h6>
                    <hr>
                </div>
            </div>
        {% endfor %}
        </div>
        
        <!--pagination-->
        <nav aria-label="Page navigation example">
            <ul class="d-flex justify-content-center my-4">
                <h5>Page {{ movies.number }} of {{ movies.paginator.num_pages }}.</h5>
            </ul>
            <ul class="pagination justify-content-center text-dark">
            {% if movies.has_previous %}
                <li class="page-item">
                  <a class="page-link text-dark" href="?page={{ movies.previous_page_number }}">previous</a>
                </li>
            {% endif %}
                <li class="page-item"><a class="page-link text-dark" href="?page=1">1</a></li>
                <li class="page-item"><a class="page-link text-dark" href="?page=2">2</a></li>
                <li class="page-item"><a class="page-link text-dark" href="?page=3">3</a></li>
                <li class="page-item"><a class="page-link text-dark" href="?page=4">4</a></li>
                <li class="page-item"><a class="page-link text-dark" href="?page=5">5</a></li>
            {% if movies.has_next %}
                <li class="page-item">
                  <a class="page-link text-dark" href="?page={{ movies.next_page_number }}">Next</a>
                </li>    
            {% endif %}
            </ul>
        </nav>
        
        <!--부트스트랩으로는 안되서  style 로 했음-->
        <!--<div class="mx-auto fixed-bottom p-3 d-flex justify-content-end">-->
        <div class="" style="position:fixed;right:30px;bottom:30px">
            <a href="#" class="float-right text-dark" ><i class="fas fa-arrow-up fa-2x"></i></a>
        </div>
    </div>
{% endblock %}

movies/templates/movies/moviePickUp.html
{% extends 'base.html' %}

{% block bb %}
    <div class="container">
        <h1>영화 data 수집 완료</h1>
        <a href="{% url 'movies:main' %}"><button> main</button></a>
    </div>      
{% endblock %}

movies/templates/movies/person.html
{% extends 'base.html'%}
<!--영화의 상세 내용을 나타내는 페이지-->

{% block bb %}
<div class="container">
    <h1 class="text-center my-5" style="font-family: 'Playfair Display SC';text-decoration: underline; ">Today's celebrity</h1>
    
    {% for data in datas %}
    <a class="col-3" data-toggle="modal" data-target=".bd-example-modal-sm{{data.num}}"><img src="{{data.profile}}" style="height:18%; width:18%" class="my-2"></img></a>

    <div class="modal fade bd-example-modal-sm{{data.num}}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content"> 
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalScrollableTitle"><b>{{data.name}}</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="text-align : center;">
                    {% if data.poster_id %}
                        <a href="{% url 'movies:detail' data.poster_id %}"><img src="{{data.poster}}" class="w-75"></img></a>
                    {% else %}
                        <img src="{{data.poster}}" class="w-75"></img>
                    {% endif %}
           
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <br><br><br><br><br>
</div>

{% endblock %}

movies/templates/movies/rating.html
<!--평점 폼-->
<form action="{% url 'movies:scoreCreate' movie.id %}" method="POST">
    {% csrf_token %}
    <select name="rating" id="rating">
        <option value="1">★☆☆☆☆</option>
        <option value="2">★★☆☆☆</option>
        <option value="3">★★★☆☆</option>
        <option value="4">★★★★☆</option>
        <option value="5">★★★★★</option>
    </select>
    <input type="submit" value="별점" class="btn btn-secondary btn-sm">
</form>

movies/templates/movies/search.html
{% extends 'base.html'%}
{% load static %}
{% block bb %}
<!--작품, 제목,배우,감독으로 원하는 영화를 검색-->
  <div class="col-md-12 p-0">
    <img src="/static/images/search2.jpg" style="width:100%; height:600px"  >
    <div class="carousel-caption">
      <h1 class=" text-black mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s" style="font-family: 'Playfair Display SC'">Todal Movie</h1>         
      <br><br><br>
      <!--영화 검색 -->
      <div class="justify-content-center">
          <form method="GET" class="d-flex justify-content-center">
              <i class="fas fa-search fa-2x"></i>
              <input type="text" name="searchword" value="{{searchword}}" placeholder="작품 제목을 검색해보세요." class="shadow-lg rounded border border-dark w-75 p-2">
              <div class="fontchange" style="font-family: 'Noto Sans KR', sans-serif;">
          </form>
      </div>
    </div>
  </div>
  <!--안좋은 방법이지만 밑에 빈 공간을 만들어주고 싶어서 사용함-->
  <div style="height:300px"></div>

{% endblock %}

movies/templates/movies/searchresult.html
{% extends 'base.html' %}
{% block bb %}
        <div class="col-md-12 p-0">
            <!--나중에 이미지 바꾸고 크기 조정해야함 & 글자 가운데 정렬-->
            <img src="/static/images/search2.jpg" style="width:100%; height:600px" class="img-responsive" >
              <div class="carousel-caption">
              <h1 class=" text-black mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s" style="font-family: 'Playfair Display SC'">Todal Movie</h1>         
                <br><br><br>
                <!--영화 검색 -->
                <div class="justify-content-center">
                    <!--작품, 제목,배우,감독으로 원하는 영화를 검색-->
                    <form method="GET">
                    <!--get 방식인데 토큰이?-->
                    <!--{% csrf_token %}-->
                    <i class="fas fa-search fa-2x"></i>
                    <input type="text" name="searchword" value="{{searchword}}" placeholder="작품 제목을 검색해보세요." class="shadow-lg rounded border border-dark w-75 p-2" style="font-family: 'Noto Sans KR', sans-serif;">
                    <!--<input type="submit", value="search">-->
                    </form>
                </div>
            </div>
        </div>
        
    <div class="container">
        <br>
        <!--resultMovie에 데이트가 있다면 영화 딕셔너리 출력 후 디테일 링크 -->
        {% if resultMovie %}
            <ul>
            <h2 class="fontchange" style="font-family: 'Noto Sans KR', sans-serif;"><strong>검색결과</strong></h2><br>
            {% for rm in resultMovie %}
                <a class="h5 text-dark" style="font-family: 'Noto Sans KR', sans-serif;" href="{% url 'movies:detail' rm.id %}">{{rm.title}}</a>
                <!--검색 결과에 이미지도 추가하고 싶은데..방법이 안떠오름-->
                <br><br>
            {% endfor %}
            </ul>
        {% else %}
            <ul>
            <!--resultMovie가 빈 리스트라면 이름을 입력해달란 메세지, -->
            <h3 class="fontchange"style="font-family: 'Noto Sans KR', sans-serif;"><strong>검색 결과가 없습니다.</strong></h3>
            </ul>
        {% endif %}
    </div>       
{% endblock %}